### ISSUE TITLE
Contenedor Docker no construye (Docker container does not build)

### ISSUE THREAD

**Issue by JorgSierra** [kiwicampus/Turtlebot-Gazebo-Navigator#5]
Hola,

Tengo un problema al correr el contenedor de Docker para el ambiente de trabajo del repositorio. Quería preguntar si este contenedor debería correr con las configuraciones que se descargan directamente del repo o es necesario modificar algo.

Te comparto un pantallazo del error que me sale a la hora de correr el comando "Docker Images: Build Image..."
![image (1)](https://user-images.githubusercontent.com/92490864/216684215-bdc37b47-6973-4e45-b31c-62b4b3676936.png)

Al cerrar y abrir VS y dar en la ventana emergente la opcion de "Reopen in container"
![image](https://user-images.githubusercontent.com/92490864/216684259-cc65d90f-d4b2-42f8-a4fd-b9b397e9d107.png)

Es posible me puedas ayudar con este problema?

Muchas gracias.

**Comment by dadaroce** [comment]
Hola, 

Dale por favor en `More Actions...` y comparte el log que te sale. Algo me dice que instalaste la version de docker-compose que no era.

**Comment by JorgSierra** [comment]
En este momento no estoy con el compu a la mano, es posible que me digas la
versión correcta para poder revisar cuando llegue a la casa.

Te envío esto a forma de correo pero apenas pueda te respondo por el foro
para hacer seguimiento.

Gracias.

**Comment by dadaroce** [comment]
Primero intenta esto: 

![image](https://user-images.githubusercontent.com/39452483/216708426-5d5b341d-fc31-49ab-9b00-cc348e9822da.png)

**Comment by dadaroce** [comment]
Igual, me queda dificil dar un diagnostico sin saber exactamente el error. Solo estoy suponiendo que ese es el problema.

**Comment by JorgSierra** [comment]
Entiendo muchas gracias, me ayuda mucho tenerlo a mano porque para la hora
que llegué a la casa en Colombia ya sería de noche y no quiero molestarte a
horas que no son.

**Comment by JorgSierra** [comment]
Con la versión `0.251.0` de la extensión `Dev Containers` el contenedor construye!

Gracias @dadaroce.
